# Generated by Django 3.2.7 on 2023-04-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='event1',
            field=models.TextField(blank=True, null=True, verbose_name='出来事1'),
        ),
        migrations.AddField(
            model_name='diary',
            name='event2',
            field=models.TextField(blank=True, null=True, verbose_name='出来事2'),
        ),
        migrations.AddField(
            model_name='diary',
            name='event3',
            field=models.TextField(blank=True, null=True, verbose_name='出来事3'),
        ),
        migrations.AddField(
            model_name='diary',
            name='event4',
            field=models.TextField(blank=True, null=True, verbose_name='出来事4'),
        ),
        migrations.AddField(
            model_name='diary',
            name='event5',
            field=models.TextField(blank=True, null=True, verbose_name='出来事5'),
        ),
    ]
