# Generated by Django 3.2.7 on 2023-04-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_auto_20230409_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='api_key',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='ChatGPTのAPI-key'),
        ),
    ]
