# Generated by Django 3.2.7 on 2023-04-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20230409_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='event1',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='出来事1'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='event2',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='出来事2'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='event3',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='出来事3'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='event4',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='出来事4'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='event5',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='出来事5'),
        ),
    ]
