# Generated by Django 3.2.7 on 2023-04-11 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0007_auto_20230409_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='event2',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='event3',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='event4',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='event5',
        ),
        migrations.AlterField(
            model_name='diary',
            name='event1',
            field=models.TextField(blank=True, null=True, verbose_name='出来事'),
        ),
    ]
