# Generated by Django 3.2.7 on 2023-04-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20230409_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='event2',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='event3',
        ),
        migrations.AlterField(
            model_name='diary',
            name='api_key',
            field=models.CharField(max_length=60, verbose_name='ChatGPTのAPI-key'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='event1',
            field=models.TextField(blank=True, null=True, verbose_name='出来事'),
        ),
    ]
