# Generated by Django 3.2.7 on 2023-04-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_diary_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='event',
            field=models.TextField(default='', verbose_name='出来事'),
        ),
    ]
