# Generated by Django 3.2.7 on 2023-06-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20230411_1238'),
        ('diary', '0013_alter_diary_event'),
    ]

    operations = [
    ]
