# Generated by Django 3.2.7 on 2023-06-27 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0014_merge_0008_auto_20230411_1238_0013_alter_diary_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='event1',
        ),
        migrations.AlterField(
            model_name='diary',
            name='api_key',
            field=models.CharField(max_length=40, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='event',
            field=models.TextField(blank=True, verbose_name='出来事'),
        ),
    ]
